project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Welcome to Bioinformatics!"
        contents:
          - index.qmd
      - section: "Session 0. HPC and Personal Cloud"
        contents:
          - 0.1_Personal_Cloud.qmd
      - section: "Session 1. Linux: The basics"
        contents:
          - 1.1_Introduction_to_Linux.qmd
          - 1.2_Loading_Software_Accessing_Data.qmd
          - 1.3_Commandline_Tools_and_Scripting.qmd
      - section: "Session 2. NGS data"
        contents:
          - 2.1_NGS_Quality_Control.qmd
          - 2.2_genome_assembly.qmd
          - 2.3_hybrid_assemblies.qmd
      - section: "Session 3. Genomics"
        contents:
          - 3.1_Genome_visualisation_and_annotation.qmd
          - 3.2_Annotating_mitochondria.qmd
      - section: "Session 4. Building phylogenies"
        contents:
          - 4.1_phylogentics_phylogenomics.qmd
          - 4.2_phylogentics_phylogenomics_extension.qmd
      - section: "Session 5. Transcriptomics"
        contents:
          - 5.1_RNAseq_processing.qmd
          - 5.2_DEG_analysis.qmd
          - 5.3_DEG_Functional_Interpretation.qmd
      - section: "Session 6. Microbial community analysis"
        contents:
          - 6.1_metabarcoding.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

