project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Session 0. HPC and Personal Cloud"
        contents:
          - index.qmd
          - Personal_Cloud.qmd
      - section: "Session 1. Linux: The basics"
        contents:
          - Introduction to Linux.qmd
          - 1_Linux_fundermentals.qmd
          - Loading_Software_Sccessing_Data.qmd
          - Commandline_Tools_and_Scripting.qmd
      - section: "Session 2. NGS data"
        contents:
          - NGS_Quality_Control.qmd
          - genome_assembly.qmd
      - section: "Session 3. Genomics"
        contents:
          - Genome_visualisation_and_annotation.qmd
          - hybrid_assemblies.qmd
      - section: "Session 4. Building phylogenies"
        contents:
          - phylogentics_phylogenomics.qmd
      - section: "Session 5. Transcriptomics"
        contents:
          - Transcriptomics_Introduction.qmd
          - RNAseq_processing.qmd
          - DEG_analysis.qmd
          - DEG_Functional_Interpretation.qmd
      - section: "Session 6. Microbial community analysis"
        contents:
          - metabarcoding.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

